name: SuperBans
main: org.kitteh.superbans.SuperBans
version: 0.0alpha
website: http://kitteh.org
author: mbaxter
description: Super banning solution
commands:
  ban:
    description: Ban
    usage: /ban playername
  unban:
    description: Unban
    usage: /unban playername
  lookup:
    description: Lookup
    usage: /lookup playername
  kick:
    description: Kick
    usage: /kick playername
permissions:
  superbans.ban:
    description: Ban
    default: op
  superbans.unban:
    description: Unban
    default: op
  superbans.lookup:
    description: Lookup
    default: op
  superbans.tempban:
    description: Temp Ban. Currently unsupported.
    default: op
  superbans.notice:
    description: Receive notices
    default: op
  superbans.kick:
    description: Kick folks
    default: op
  superbans.all:
    children: 
      superbans.ban: true
      superbans.unban: true
      superbans.lookup: true
      superbans.tempban: true
      superbans.notice: true
      superbans.kick: true